### ISSUE TITLE
複数ボタン設置

### ISSUE THREAD

**Issue by kobbeko** [TakutoYoshikai/rcjs#1]
下記のプログラムで先に押したボタン（TBS、文化放送)しか動作しません。
TBSを押すと、TBSは動作しますが、その後文化放送を押しても変化しない。
どこが間違っているのか教えてください。

const Remocon = require("rcjs");

const remocon = new Remocon();

const execSync = require("child_process").execSync;

remocon.addButton("TBS", function() {
  execSync("/home/pi/radiko.sh -t radiko -s TBS >> /dev/null");
});
remocon.addButton("文化放送", function() {
  execSync("/home/pi/radiko.sh -t radiko -s QRR >> /dev/null");
});

remocon.start(3000);

**Comment by TakutoYoshikai** [comment]
@kobbeko 
execSyncの箇所をconsole.logに変えて試したところ、関数が呼ばれていて、正常に動いているように見えました。
おそらくexecSyncのコマンドに問題があるのではないでしょうか？

**Comment by TakutoYoshikai** [comment]
もしくは、execのsyncだから問題があるのかもしれません。
同期処理としてコマンドを実行してると、そのコマンドが終わるまで処理が進んでいないのかも

**Comment by TakutoYoshikai** [comment]
> もしくは、execのsyncだから問題があるのかもしれません。 同期処理としてコマンドを実行してると、そのコマンドが終わるまで処理が進んでいないのかも

その場合、

```javascript
const exec = require("child_process").exec;
exec("/home/pi/radiko.sh ....");
```

みたいに実行すると良いかもしれません。

**Comment by kobbeko** [comment]
アドバシスありがとうございます。

2022年8月21日(日) 22:32 tanaka nobuyuki ***@***.***>:

**Comment by TakutoYoshikai** [comment]
自分でも再現しました。
コールバックが終了していないと、他のボタンが押されたときのコールバックが呼ばれないみたいなので、これは別のissueを立てる必要がありそうです。

@kobbeko 報告ありがとうございました。

**Comment by kobbeko** [comment]
非同期で動作させるで剣先したら、下記の記事がありました。
重要なのは実行されるスクリプトの出力を廃棄することです。ファイルに書き出すという意味ではなく、データそのものを虚無に返しています。
試しに、2>&1 &を追加したら、動作しました・

2022年8月21日(日) 22:28 TAKUTO YOSHIKAI ***@***.***>:
